### ISSUE TITLE
举报（20191024）

### ISSUE THREAD

**Issue by ydleetmmu** [shadowquark/comments#3]
不知道归档在日志（archives）而非动态（yyFish）的可否在issue讨论，但是读了《举报》这则日志后，有一个想要请教和讨论的问题。

首先我对您的关于“张力”和“价值冲突”这两个论断非常认同。尤其是“张力”这样的描述非常贴切。我想讨论的内容是举报这个行为本身的一些细节。您在日志中讨论的内容起因是互联网上针对言论（爆粗）的举报，但其实正文中讨论了广泛意义上的举报。我的讨论关注的是这一部分更广泛意义上的举报。我观察到您举出的一些例子在解释力上有些不充分。
问题来源于您所举的两个例子：
> 假如某甲偷了我的钱，我去报案，这不叫举报，因为这涉及了我被偷钱这个私人问题。一些举报的支持者会反驳我说「如果看到潜逃的杀人犯应否应该举报呢？」实际上从古至今，对于举报杀人犯，都有一个公权力发海捕公文、通缉令的过程。换句话说，对于重大刑事事件，公权力会主动诉诸举报。显然公权力不是事事都有如此明确地发出举报请求的作派。这种举报非常特殊，它既是对犯罪这种违反公权力行为的举报，也是因为使自身及家人受到威胁之人危害了私人安全。换句话说，作为一个举报的反对者。假如某甲和某乙有仇，某甲杀了某乙，我是不会举报某甲的。因为某甲没有威胁我及家人朋友的安全，他只是报私仇。对他执法，是公权力的责任，不是我的责任。所以我一直说，我是很可能和杀人者打虎武松作朋友的。相反，如果某地出现了连环杀人案、无差别奸杀案。那么我有了线索一定报案，因为我及亲友、乃至一切无辜人员的私人安全都受到了威胁。我理应选择保护我自己和他们。

在这里，您认为当自身的利益（生命安全）受到威胁的时候，这个类型的“举报”并非下文所要讨论的范畴。但是可以看到，在第二个例子，“甲乙有私仇”的情形下，也隐含着自身利益受到威胁，只是这种威胁的程度非常轻微。比如有这样的可能，你知道甲和乙有仇，但仇怨不足以重至杀人。在杀人事件发生后，您对于甲发生不理智行为可能性的评估就要增高了，因为这隐性威胁着您和家人的安全。如果以后甲也和自己或自己的家庭成员发生一些不大的矛盾（这显然是有可能的，因为不太可能存在完全和谐的邻里），您自己也同样会处于“私人安全”受威胁的状态。同样以飞叶子来举例，如果您的朋友吸食的是成瘾性更高的毒品或者涉于赌博，那么对个人安全的威胁就会明显升高。这个时候“子为父隐，父为子隐”是否仍是您的选择？

我个人觉得，按照您所举的例子，对于很多事情是否举报，其实是一个基于个人概率判断的有弹性选择。对于连环杀人犯，因为他威胁到自身安全的概率很大，所以应当举报；对于独立发生的仇杀，因为他威胁到自身安全的概率不大，所以不应当举报。这可以推论到学生时代一个很困扰我的问题，就是同学的考试作弊是否应该举报。虽然我一直没有举报，但这是来源于家庭教育而非自身价值判断。在不重要的考试中，因为他人作弊对我利益的影响不大，所以没有举报的动力，但是在一些重要的考试中，他人的作弊严重影响了我的利益，我一直忍着冲动才没有去举报。这个事情跟您所举的“海捕公文”很像，都是官方张榜或提供举报通道，同时对方的行为也影响到了自身的利益。您所述的这两个例子是否也和我所列举的考试作弊举报一样，是个人对影响自身利益的概率及程度判断的差异决定了要不要举报？

另外一个我所考虑的内容是：由于这种价值和概率判断是主观的，那么对于您举的另一个例子，“未成年人性行为”，总会有人对这类行为不适，当这种不适感达到阈值，严重影响了他的心理和正常生活，他就会选择举报这种行为。您作为未成年人性行为的支持者，是否认为他们的行为也是正当和可理解的？因为这种“举报”的类型并非您所反对的举报。

**Comment by shadowquark** [comment]
首先感谢您的回复，以及抱歉因为搬家、之前一直还没有彻底安定下来，就没有抽出时间回答您如此认真的讨论。

首先必须明确一点，我认为社会中的道德准则完全是主观的，即道德价值体现在个体对自身道德律的践行上。换句话说，一个社会中有越多人认真践行自己的道德准则，那么我认为这个社会越道德，换句话说，这个社会中包含更多的道德价值。这种价值可以给这样的社会带来大量实际利好。在这个『自律道德』而非『公共道德』或『绝对道德』的理解下，就无法脱离一种你所理解到的主观性。因为道德律本身就是来自个体自身，而非某种公共的『应该』。

公权力保障我们的生命权、财产权、等等，所以当我们感受到相关权利受到侵害、或存在被侵害的风险，但公权力的行使、无法达到完美效率的时候，『举报』属于行使正当的公权力赋予的权利。这种『举报』我们最好称为『报案』以作区别。所以第一个我们要关注的重点是，我们想报案的行为是不是被公权力所不允许。据我所知『和未成年发生性行为』在中国并不一定违法，只有和十四岁以下的未成年有性接触才违法。那么在这种法律背景下，只有当一个人有和未性成熟的个体［不满十四岁］发生性接触的真正意义上的『恋童癖』时，他才既违法，又对我的孩子、我亲戚的孩子、朋友的孩子造成风险，才牵扯到报案问题。站在不满这种立法的人的角度，他们应该推动立法，并消耗自己的社会资源保护自己的孩子。即，当一个理念没有变成公共理念的时候，人们要么扩大其公共性，要么自己进行额外投入满足自己的诉求，或者两者并行。在另一个法律框架下，比如美国一些州的法律，加拿大、澳大利亚的法律，可能和所有未成年发生性关系都违法。这种情况下，站在我的立场，我应该去讨论怎么移除一个恶法，就像人们讨论怎么把禁止堕胎移除一样，而无法谴责一个不希望自己的未成年孩子和成年人发生性关系的父母的报案。如果类比到考试，高校作弊，中小学考试［这里是站在学生家长的角度，后面会提到学生的角度］，我觉得都没有理由举报，因为没有公权力管理这样的考试。但是中高考，在中国是有特殊法律规定的，是入刑的。在国家组织的考试中作弊、帮助他人作弊，都触犯刑法，这时候就属于『法律赋予了人人平等的在国家组织的考试中公平竞争的权利』，人们当然可以报案。只是在我的个人道德准则中，我是可以和杀人犯做朋友的，当然也可以和高考作弊的人做朋友。但这只是我个人的道德情操，我不会觉得报案者有任何问题。显然假如人们不能根据法律，声索公权力所保障的权利，那法律也就没屁用了。这是我想首先明确的『举报』和『报案』的区别。

在明确了『法律赋予的权利』之外你提到了一个重点，就是『存在风险』的判断标准。当然你可以认为，存在风险的判断标准是非常主观的。有的人是看到一个违法分子就觉得它有可能无差别犯罪伤害其它人。有的人看到一个未成年人和成年人谈恋爱，就可能觉得这个成年人就是找未成年人骗炮，所有未成年人都很危险。我没法阻止有些人有这种认识。但是我认为如果有人具有如是的道德情操，那么他们应该用同样的道德律要求自己。这是我对道德的根本理解，即自律道德。换句话说，比如一个人觉得 A 报复了 B，就是无差别危害所有人、将所有人至于风险中。那么这样的人，最好也不要对任何人做任何不好的事情，否则他就不是在报复仇人、或发泄个人情绪，而是无差别威胁所有人的安全。而对于我来说，我觉得假如有人强奸了我女儿，我一定崩了他。所以假使有别的人因为同样原因崩了人，我不会觉得这个人就因此威胁了我的家人。假如我是武松，我会做一样的事，所以我不觉得武松无差别威胁了我。我们看到大量的举报都是『严于律人』加上『宽以待己』。我最常遇到的是，A 骂了我，我回骂，A 举报我，我的发言被删了，甚至号被封了，他骂我的话还在。再举一例，如果一个人真的觉得『区别对待』就是『歧视』，那么他不能区别对待任何人，甚至不能区别对待自己的父母和朋友，否则就是在歧视某一方。不能因为别人的区别对待，就指责别人歧视，而自己每天都在区别对待所有人，就不叫歧视。相反，我认为任何人看别人不爽都可以爆粗口，那别人当然可以对我爆粗口。这是我的道德律完全允许的。我认为那种『道德律践行』上的不对等，甚至本末倒置，就是最严重的不道德，是社会道德的最严重缺失。那么虽然我承认『对风险理解』的主观性，我依然有着一个客观标准去判定哪些人是『举报死全家的傻屄』，哪些人只是对道德的理解和我不同。我从小班里就有那种真正意义上的好孩子，不但我犯了错他会告老师，他还从来不会犯同样的错。当然这是对于未成年人来说，法律对于未成年人还不是主要的训诫手段。我们假定承认［事实上法律也是这么规定的］未成年人主要依赖老师和家长的权威进行训诫的，这种规训会在人们成年后被法律所替代，即回到之前谈到的公权力赋予的权利的问题。比如我上课聊天打扰了他，他告老师，那么他一定从不在课上聊天。我认为这种人是道德的，只是道德律与我不同。希望这段解释解决了你关于『主观性』的困惑。

**Comment by ydleetmmu** [comment]
谢谢您的回应，给了我很好的启发。
