### ISSUE TITLE
博客的搜索功能有bug

### ISSUE THREAD

**Issue by ilovecwr** [shadowquark/comments#8]
case：搜索关键词“鲁菜”只返回一个结果
![B077FB71-D313-4023-A261-9FF314ACBA54](https://github.com/shadowquark/comments/assets/18585565/c9952617-a600-41bb-80e2-11d49440d433)

**Comment by shadowquark** [comment]
搜索功能应该是只负责大致定位，而不是每个出现的词都能搜索到一次。
